export const SHOW_CART = "SHOW_CART";
export const ADD_TO_CART = "ADD_TO_CART";
export const ADD_PRODUCTS = "ADD_PRODUCTS";
export const SHOW_PRODUCTS_IN_CART = "SHOW_PRODUCTS_IN_CART";
export const HIDE_PRODUCTS_IN_CART = "HIDE_PRODUCTS_IN_CART";
export const REMOVE_PRODUCT_FROM_CART = "REMOVE_PRODUCT_FROM_CART";
export const SET_PRODUCTS = "SET_PRODUCTS";
export const FETCH_PRODUCTS = "FETCH_PRODUCTS";